#
# fly.toml file generated for Nightscout see https://nightscout.github.io/
#

#---------------------------------------------------------------------------------
# CHange the app value to your site name. (i.e. sitename to have sitename.fly.io
#---------------------------------------------------------------------------------
app = "felix-nightscout"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

#----------------------------------------------------------------------------------
#
# Review and modify the variables below and adapt them to your needs
# The first three API_SECRET, DISPLAY_UNITS and MONGODB_URI are MANDATORY
#

[env]
# Preferred BG units for the site: 'mg/dl' or 'mmol/l' (or just 'mmol').
DISPLAY_UNITS="mg/dl"

# Plugins to enable for your site. Must be a space-delimited lower-case list. Include the word 'bridge' here if you are receiving data from the Dexcom Share service.
ENABLE="connect careportal dbsize rawbg iob maker cob bwp pushover override cors"

# These are the env vars for setting up syncing with Glooko
CONNECT_SOURCE="glooko"
CONNECT_GLOOKO_EMAIL="devon.c.estes@gmail.com"
CONNECT_GLOOKO_TIMEZONE_OFFSET="1"
CONNECT_GLOOKO_ENV="eu"
CONNECT_GLOOKO_SERVER="de-fr.api.glooko.com"

# Default setting for whether or not these plugins are checked (active) by default not merely enabled. Include plugins here as in the ENABLE line; space-separated and lower-case.
SHOW_PLUGINS="careportal dbsize"

# simple' and/or 'predict'. Simple alarms trigger when BG crosses the various thresholds set below. Predict alarms use a formula that forecasts where the BG is going based on its trend. You will *not* get warnings when crossing the BG thresholds set below when using the predict type.
ALARM_TYPES="simple"

# Urgent High BG threshold triggers the ALARM_URGENT_HIGH alarm. Set in mg/dL or mmol/L as set in DISPLAY_UNITS variable.
BG_HIGH=250

# Urgent Low BG threshold triggers the ALARM_URGENT_LOW alarm. Set in mg/dL or mmol/L as set in DISPLAY_UNITS variable.
BG_LOW=55

# Low BG threshold triggers the ALARM_LOW alarm. Set in mg/dL or mmol/L as set in DISPLAY_UNITS variable.
BG_TARGET_BOTTOM=80

# High BG threshold triggers the ALARM_HIGH alarm. Set in mg/dL or mmol/L as set in DISPLAY_UNITS variable.
BG_TARGET_TOP=180

# Default setting for new browser views for the Urgent High alarm (triggered when BG crosses BG_HIGH). ('on' or 'off')
ALARM_URGENT_HIGH="on"

# Default setting for new browser views for the Urgent Low alarm (triggered when BG crosses BG_LOW). ('on' or 'off')
ALARM_URGENT_LOW="on"

# Default setting for new browser views for the High alarm (triggered when BG crosses BG_TARGET_TOP). ('on' or 'off')
ALARM_HIGH="on"

# Default setting for new browser views for the Low alarm (triggered when BG crosses BG_TARGET_BOTTOM). ('on' or 'off')
ALARM_LOW="on"

# Default setting for new browser views for an urgent alarm when CGM data hasn't been received in the number of minutes set in ALARM_TIMEAGO_URGENT_MINS. ('on' or 'off')
ALARM_TIMEAGO_URGENT="on"

# Default setting for new browser views for a warning alarm when CGM data hasn't been received in the number of minutes set in ALARM_TIMEAGO_WARN_MINS. ('on' or 'off')
ALARM_TIMEAGO_WARN="on"

# Default setting for new browser views for the number of minutes since the last CGM reading to trigger an ALARM_TIMEAGO_URGENT alarm.
ALARM_TIMEAGO_URGENT_MINS=30

# Default setting for new browser views for the number of minutes since the last CGM reading to trigger an ALARM_TIMEAGO_WARN alarm.
ALARM_TIMEAGO_WARN_MINS=15

# Default setting for new browser views for whether Night Mode should be enabled. ('on' or 'off')
NIGHT_MODE="on"

# Default setting for new browser views for the color theme of the CGM graph. ('default' 'colors' or 'colorblindfriendly')
THEME="colors"

# Default setting for new browser views for the time mode. ('12' or '24')
TIME_FORMAT=24

# U value over which the bolus values are rendered on the chart if the 'x U and Over' option is selected.
BOLUS_RENDER_OVER=0.5

#   DO NOT MODIFY ANYTHING BELOW
# //////////////////////////////////////////////////////////////////////////////////////////////

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 1337
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
